services:
    api:
        build:
            context: .
            target: development
        environment:
            MONGO_DATABASE: ${MONGO_DATABASE}
            MONGO_USER: ${MONGO_USERNAME}
            MONGO_PASSWORD: ${MONGO_PASSWORD}
            MONGO_PORT: ${MONGO_PORT}
            MONGO_URL: ${MONGO_URL}
        volumes:
            - ./:/usr/src/app
            - /usr/src/app/node_modules
        ports:
            - ${ANTLERS_SERVER_PORT}:5000
        command: npm run dev
        depends_on:
            - mongodb
    mongodb:
        image: mongo:6-jammy
        environment:
            MONGO_INITDB_DATABASE: ${MONGO_DATABASE}
            MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
            MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
        ports:
            - ${MONGO_PORT}:27017
        volumes:
            - ./database:/data/db
