services:
    test-db:
        image: mongo:6-jammy
        environment:
            MONGO_INITDB_DATABASE: ${MONGO_DATABASE}
            MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
            MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
        ports:
            - ${MONGO_PORT}:27017
        volumes:
            - ./database_test:/data/db
